### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by berecont**
add PDF version

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
This is only correct if you use the free version of the FPDI PDF-Parser. If you buy and install the commercial version, you will be able to use any PDF. I think this should be mentioned in the mPDF notes below. Suggestion:

> * By default only PDF documents up to PDF version 1.4 are supported by the FPDI PDF-Parser used by mPDF. However, you can [buy the commercial version](https://www.setasign.com/products/fpdi-pdf-parser/) in order to be able to convert any PDF.

**Comment by fritzmg** [comment]
I made some changes - @berecont wdyt?

**Comment by berecont** [comment]
OK, that sound good for me

**Comment by fritzmg** [comment]
Thank you @berecont 👍

**Pull request merged**
